### ISSUE TITLE
InputEventSingleScreenSwipe sometimes not working

### ISSUE THREAD

**Issue by dqdthanhthanh** [Federico-Ciuffardi/GodotTouchInputManager-Demo#3]
Sometimes when I open the app, the swipe can't be done. Other operations are still normal. The swipe operation only works again when opening and closing the app again and again. But the problem is still encountered

**Comment by Federico-Ciuffardi** [comment]
Some questions so that I can help you:
* What version of Godot do you use?
* What version of GDTIM do you use?
* What OS do you use?
* Does this happen in the demo from this repo, or in a personal project of yours using GDTIM?
* Is this error reproducible? Can you tell me what steps I have to follow to make it happen?

**Comment by dqdthanhthanh** [comment]
- Thanks, I use Godot 3.5 plugin ver 2.1.2. 
- I working on pc (both windown and mac ) and got this error but not very often.
- I also tested the demo scene on mobile (both ios and android). The most obvious error when test on mobile. Sometimes when opening the app, InputEventSingleScreenSwipe doesn't work. Which I have to restart the app. However, other InputEvents still work properly except for InputEventSingleScreenSwipe.
- The function that I use to test:

func _input(event):
	if event is InputEventSingleScreenSwipe:
		...
                ...

- Sometimes when opening the app, things in "if event is InputEventSingleScreenSwipe:" not running. You have to close and reopen the app to get it to work.
- Maybe there's something wrong with InputEventSingleScreenSwipe when opening the app from start.
- You can easily check this error when you first install the app on mobile. I usually install to iphone to test.

**Comment by Federico-Ciuffardi** [comment]
I am not able to reproduce the error, I tried it with https://github.com/Federico-Ciuffardi/GodotTouchInputManager-Demo/releases/tag/v2.1.2 (unmodified) on android and linux. I have opened and closed the app multiple times and swipes are always recognized correctly.

If you made any modifications to the demo please try the unmodified version. And also tell me what changes you made so I can try to reproduce the error.

If you did not modify the demo, tell me what devices you are testing on and I will wait for more reports of this error since with the current information I don't know what could be going wrong.

**Comment by dqdthanhthanh** [comment]
Looks like this bug only appears on old godot 3. I no longer get the error on the latest godot 3.52. Many thanks.
